# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Students
    url: '#students'
    weight: 20
  - name: Media
    url: '#photoslide'
    weight: 30

  - name: CV
    url: 'CV'
    weight: 40
  - name: News
    url: '#talks'
    weight: 50
  - name: Publications
    url: '#publications'
    weight: 60

  - name: ROSES
    url: '#roses'
    weight: 70

  - name: Contact
    url: '#contact'
    weight: 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
